env:
  browser: true
parser: "vue-eslint-parser"
extends:
  - plugin:@typescript-eslint/recommended
  - eslint:recommended
  - plugin:vue/essential
parserOptions:
  ecmaVersion: 13
  parser: '@typescript-eslint/parser'
  sourceType: module
plugins:
  - vue
  - '@typescript-eslint'
rules: {}
